### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [tang-nina/Parstagram#1]
It looks like your video walkthrough doesn't seem to show some of the required stories as follows:

- User sees app icon in home screen
- The current signed in user is persisted across app restarts
- User can tap a post to view post details, including timestamp and caption.

Can you update this and resubmit?

**Comment by tang-nina** [comment]
Hi, I am pretty sure my walkthrough does show all of that. At the beginning of the walkthrough, there is an instagram icon above where the user can sign up or login, so this satisfies "user sees app icon in home screen." After I compose a post in the walkthrough, the app closes to the Android phone home screen because I stopped the app on Android studio and restarted it. Once the app reopens, I am still logged in as "newaccount5", thus satisfying "The current signed in user is persisted across app restarts." Finally, near the end,  my walkthrough clearly shows that I tap on a post of a clock tower which takes the user to a post details page, that displayed the caption ("test7") and the timestamp ("2 days ago.").

**Comment by tang-nina** [comment]
@codepathreview Please reply when you see my above ^ explanation and let me know if you still need me to do something.

**Comment by tang-nina** [comment]
@codepathreview I have just resubmitted my comments above on courses.codepath.org in case "resubmit" meant on that website, and not here.

**Comment by codepathreview** [comment]
Thank you for letting us know!

Nice work, Nina. We put together a detailed Project 4 Feedback Guide here: (http://courses.codepath.org/snippets/android_university_fast_track/feedback_guides/project_4_feedback) which covers the most common issues with this project. Read through the feedback guide point-by-point to determine how you could improve your submission.

We hope you enjoyed the course and learned a lot in the process and look forward to see what you build for your final internship project!
 
/cc @codepathreview
